# Generated by Django 5.1.3 on 2025-01-29 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_address_remove_user_user_credit_user_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_active_code',
            field=models.CharField(default='tJiB1Xp0i8us2UZVS9zv2XXa3dSkOOuXOi5v4SKwvUGQBhO41LVc4W6NQfApld5i', max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='no_pfp.png', upload_to='profile_pictures/'),
        ),
    ]
