# Generated by Django 5.1.3 on 2025-01-31 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_email_active_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_active_code',
            field=models.CharField(default='vKfwjhdnVYIExqiUle5scTI0P54cZR2JJLJetWW9tpfU6L1AYpM4W15QJNSuidK0', max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='images/no_pfp.png', upload_to='profile_pictures/'),
        ),
    ]
