# Generated by Django 5.1.3 on 2025-01-31 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_email_active_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_active_code',
            field=models.CharField(default='Z8sSNcsKdx4uqvSpm4HwaUYUzoUEctJj3IPe1dNMFjclS9IE57odvbO1PwFcgrtz', max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
