# Generated by Django 5.1.3 on 2025-01-31 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_email_active_code_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_active_code',
            field=models.CharField(default='VeYLY29T81lI1mCt4T8yGsIkrGb8JzhsLl0au5GpeBDxTmn99POj8UmVtk02nBjZ', max_length=64),
        ),
    ]
