# Generated by Django 5.1.3 on 2025-01-31 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_user_email_active_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_active_code',
            field=models.CharField(default='ZsJvCnSkViAp19uoug3wwn4pFxDXa3FFDrNgJwacz81tvt9D1XdsczgRUTvozZsY', max_length=64),
        ),
    ]
