# Generated by Django 5.1.3 on 2025-02-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_user_email_active_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_active_code',
            field=models.CharField(default='wnf1BBoem65tHuf2KOJwG7m3QQCGHgHxtNi6VVzwfTIjgUq4kPm1Kc3d2GQ9GndJ', max_length=64),
        ),
    ]
