# Generated by Django 5.1.3 on 2025-02-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_user_email_active_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_active_code',
            field=models.CharField(default='XIHS3mO5ilVchCKUrKs6D10PCmSJffdRmwazpEfeRvvLdOWje3xIVfo8M0Jt6x18', max_length=64),
        ),
    ]
