# Generated by Django 5.1.3 on 2025-02-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_user_email_active_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_active_code',
            field=models.CharField(default='H8lFSJjzxMC7f9pCjzQRnV0LaAcz2nS4DppRH6Lqh3mo0LgaWzyYLqHAWtlUKqYZ', max_length=64),
        ),
    ]
