# Generated by Django 5.1.3 on 2025-02-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_user_email_active_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_active_code',
            field=models.CharField(default='tb97bVfwvNtpzBtfoX0IBWP8fLbqKcQ4EtrZs4cg14m9ASo9lMetgUnOlcx8oVbW', max_length=64),
        ),
    ]
