# Generated by Django 5.1.3 on 2025-02-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_user_email_active_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_active_code',
            field=models.CharField(default='SMV9hysq2i9YV8SA2eTz3ezCzKhyYA9oevGkgN4EkHWB2eqIHAgizvypbRhDESI0', max_length=64),
        ),
    ]
