# Generated by Django 5.1.3 on 2025-02-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_user_email_active_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_active_code',
            field=models.CharField(default='zDN7COsWEuIm9GzdJDkhI2ci8Gtp5yJmQvjXI59anF1nCIqlJOvnw3zdXdEZErMP', max_length=64),
        ),
    ]
