# Generated by Django 5.1.3 on 2025-02-27 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_user_email_active_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_active_code',
            field=models.CharField(default='oGeWTErGYtV0ZKp5Du4V8R1Tlq4S5B3cHe7qjzkxRiJCGDI84WTjqlFkd6tYtSeP', max_length=64),
        ),
    ]
