# Generated by Django 5.1.3 on 2025-02-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_user_cover_picture_alter_user_email_active_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='website',
            field=models.URLField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_active_code',
            field=models.CharField(default='8GL9ZTDNkMOOUaMNJlYz8UFTTpSSVvzJdroAV2ooNpTX05aUr7ydAXzlpPJ3aNDL', max_length=64),
        ),
    ]
