# Generated by Django 5.1.3 on 2025-03-03 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_user_website_alter_user_email_active_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_active_code',
            field=models.CharField(default='GCIUwKh8zUMneKDHB9tMyYLDUUWnWygmL1GZx6GgAF6nlhYuB6bsSR0JaDG23rhK', max_length=64),
        ),
    ]
