# Generated by Django 5.1.3 on 2025-03-03 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_tag_name_alter_tag_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='retweet',
            name='text',
            field=models.TextField(max_length=450, null=True),
        ),
    ]
