# Generated by Django 5.1.3 on 2025-02-27 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_tag_name_alter_tag_slug'),
        ('notification', '0002_notification_sender_notification_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='link',
        ),
        migrations.AddField(
            model_name='notification',
            name='tweed_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_tweet', to='core.tweet'),
        ),
    ]
