# Generated by Django 5.1.3 on 2025-02-27 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_remove_notification_link_notification_tweed_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='tweed_id',
            new_name='tweet_id',
        ),
    ]
